name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 13.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm install -g firebase-tools
      - run: firebase setup:emulators:firestore
      - run: npm run emu:start:firestore &
      - name: エミュレータの起動待機...
        run: sleep 10
      - run: npm run ci-test
        env:
          CI: true
